### ISSUE TITLE
Request - Can we have the model summary file which we already generate in DFL; act as changelog 

### ISSUE THREAD

**Issue by varunpro** [faceshiftlabs/DeepFaceLab#136]
**Expected behavior**
-------------------------------------------------------------------------------------------------------------------------------

I am trying different models on my end; with different values for different iterations as training and testing the results to see how they turnout as video at end – and how that can be used in different circumstances ……

A screenshot is attached to show – how they are saved at the moment:

![70885383-bb22dd80-1ffe-11ea-8349-528de04989e8](https://user-images.githubusercontent.com/56723430/112746570-3e3a2e00-8fcd-11eb-95e2-c7b0a07c146e.png)

**Actual behavior**
-------------------------------------------------------------------------------------------------------------------------------------

As probably visible from the screenshot; it’s hard to keep track of them as time goes by …

     •	Also, after a month or so, if I were to come as see these naming scheme again, would be even hard for me to 
            remember what was implied at the time of running them or saving them.
     •	lastly, if shared with someone else to work with; if nothing else it's real cumbersome to explain to them; how 
            & what that naming scheme means etc...

**Request**
-------------------------------------------------------------------------------------------------------------------------------------

Can we have the model summary file which we already generate in DFL; act as changelog –

Wherein if a model is run with different settings from before:

     •	it reflects the older summary and
     •	then reflects below the new summary (with new values etc…)

**Advantages**
--------------------------------------------------------------------------------------------------------------------------------------

     •	easy to share with people with transparency
     •	can always count back what actions were taken so the model ended up looking as result; anytime.
     •	faster testing time of DFL settings at user end; maybe even debugging

P.s - was earlier posted here … https://github.com/iperov/DeepFaceLab/issues/522

**Comment by jmhummel** [comment]
Perhaps something like a diff output might be useful, where the options change trigger saving a Summary_diff.txt file, using the same "-"/"+" convention?
![git-diff](https://user-images.githubusercontent.com/1432270/113699800-e82f4f80-968a-11eb-9272-78329ea6c31f.png)

**Comment by jmhummel** [comment]
Of course, the above screenshot is possible to generate currently, using the `diff` CLI tool, and two separate summary files. Here is an example I just created by using it:
![Screenshot_20210406-035749_JuiceSSH](https://user-images.githubusercontent.com/1432270/113701085-8a036c00-968c-11eb-9608-b31ee9674577.jpg)

**Comment by jmhummel** [comment]
You could also consider source controlling your models, creating a local git repo for the model directory, and checking in changes. Then it's easy to go back to a previous model, or view the model summary changes, without needing to make separate copies.

**Comment by varunpro** [comment]
> You could also consider source controlling your models, creating a local git repo for the model directory, and checking in changes. Then it's easy to go back to a previous model, or view the model summary changes, without needing to make separate copies.

Appreciate the idea  .. it seems this shall be very useful in even more ways than I was contemplating...  😎

P.s - I am not a coder/ programmer … if I get stuck I might seek your guidance again.

**Comment by jmhummel** [comment]
No problem. Since we have two good work-arounds (`diff`, git/source control), I'll close the issue now if you don't mind.
