### ISSUE TITLE
Web UI for remote training doesn't work on windows

### ISSUE THREAD

**Issue by voltuz** [faceshiftlabs/DeepFaceLab#154]
Added the lines of code needed for the Web UI to run as described in the readme file but it returns this error:

![image](https://user-images.githubusercontent.com/68356371/130704454-90b9e989-ad07-4b41-ab3f-98d71b3ab245.png)

**Comment by jmhummel** [comment]
Yea

**Comment by jmhummel** [comment]
Two additional pip packages are required to use it:
```
Flask==1.1.1
flask-socketio==4.2.1
```
I'm not a Windows user (I use Ubuntu 20.04 instead), so I normally just run `pip install -r requirements-cuda.txt.

With the windows pre-built version, you'll have to figure out how to install additional packages into the environment. I'm sorry I can't be of any more help there, but if you ask around, someone else may know how to do this.

**Comment by voltuz** [comment]
Hi jh it's a pleasure speaking to you!
I managed to install the dependencies by activating the dfl environment. Installing them with a regular cmd didn't work
