### ISSUE TITLE
sharp upper edge issue with the new forehead masks.

### ISSUE THREAD

**Issue by jejz** [faceshiftlabs/DeepFaceLab#26]
![image](https://user-images.githubusercontent.com/19254175/63266482-4c23bb00-c290-11e9-9772-28c45b25c62c.png)
same issue as the chin before. 
the same iperov fix could be added here as well.

**Comment by jmhummel** [comment]
duplicated by: https://github.com/faceshiftlabs/DeepFaceLab/issues/25
