### ISSUE TITLE
Ping Pong broken

### ISSUE THREAD

**Issue by camjac251** [faceshiftlabs/DeepFaceLab#76]
I believe the upstream merge broke ping pong on the master branch.

I noticed that with the two `batch_size` and `batch_cap`, only `batch_size` is used whether or not the ping pong option is enabled. With it on, changing the batch size field doesn't change `batch_size` but does change `batch_cap`, but then when training it uses `batch_size` and no ping pong.

**Comment by jmhummel** [comment]
ping pong feature removed
